# Generated by Django 2.0.5 on 2018-05-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_author', models.CharField(max_length=10)),
                ('book_intro', models.TextField()),
                ('book_cover_link', models.CharField(max_length=512)),
                ('type_of_book', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Submit_book_from_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_author', models.CharField(max_length=10)),
                ('type_of_book', models.CharField(max_length=10)),
                ('submit_from', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Update_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20)),
                ('book_author', models.CharField(max_length=10)),
                ('book_intro', models.TextField()),
                ('book_cover_link', models.CharField(max_length=512)),
            ],
        ),
    ]
