# Generated by Django 2.0.5 on 2018-05-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncBook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submit_book_from_user',
            new_name='Add_book_from_user',
        ),
    ]
